### PR TITLE
Adding "Hamming distance" as a distance metric

### PR DESCRIPTION
**Pull request by sky-2002**
This PR attempts to add the hamming distance metric to weaviate.

### CODE REVIEW

**Comment by sky-2002** [comment]
I agree with the CLA

**Comment by bobvanluijt** [comment]
@antas-marcin / @etiennedi  – can you please let me know what needs to be updated [here](https://github.com/semi-technologies/weaviate-io/blob/main/developers/weaviate/current/vector-index-plugins/distances.md)?

**Comment by etiennedi** [comment]
We'll take care of the docs changes as part of the release, as this mostly depends on _when_ this will be merged. (Most likely v1.15 timeline)

**Comment by bobvanluijt** [comment]
Even better!

PS:
Thanks for the contribution @sky-2002 🙏

**Pull request merged**
