### PR TITLE
gh-885: Remove playground from docker compose

### PR DESCRIPTION
**Pull request by bobvanluijt**
@etiennedi if the merge is part of the master branch is enough for sandboxing.

### CODE REVIEW

**Comment by etiennedi** [comment]
@bobvanluijt I'm not sure I understand this issue. You say the "playground should run as its own service". The whole point of docker-compose is to compose independent services together.

If you don't want it running in a specific use case, you could either
a) create a new docker-compose file that is specific to this particular use case
b) use the existing docker-compose file but only start up the services you want

It was added to the `docker-compose/runtime/docker-compose.yml` because we said that's the entrypoint for a user to try it out and for trying it out they need the playground. Removing it here, we are now saying the try-out user doesn't need the playground anymore?

**Comment by bobvanluijt** [comment]
@etiennedi would it be possible to ignore a service on startup?

**Comment by etiennedi** [comment]
Absolutely, if you have the following `docker-compose.yaml`:

```yaml
version: "3.4"
services:
  service1:
    image: ubuntu
  service2:
    image: ubuntu
  service3:
    image: ubuntu
```

and you want to ignore `service2`, you could simply do: `docker-compose up service1 service3`

**Comment by bobvanluijt** [comment]
Ha, thanks @etiennedi. I was actually looking to _ignore_ a service, but this also works. Thanks

**Pull request closed without merging**
