### PR TITLE
General updates based on version 1.2

### PR DESCRIPTION
**Pull request by bobvanluijt**

### CODE REVIEW

**Comment by bobvanluijt** [comment]
Friendly reminder @etiennedi 😊👍

**Comment by etiennedi** [comment]
> Friendly reminder @etiennedi 😊👍

Blocked some time for this tomorrow.

**Comment by etiennedi** [comment]
I'm going to respond via email to be able to add some internal (non-public) remarks.

**Comment by etiennedi** [comment]
Closing this PR, as we have already updated the README in the meantime and the changes in here are (at least in part) no longer relevant. Feel free to issue a new PR if you'd like to keep some of the changes proposed in here.

**Pull request closed without merging**
