### PR TITLE
nit: Improve GitHub Community Standards Score

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
GitHub will give a higher community standards score to repos with CONTRIBUTING.md files.

### What's being changed:

Changing the filename for contributing on Weaviate so that the repo can benefit from all the ways in which the Community Standards improve discoverability.

### Review checklist

- [x] Documentation has been updated, if necessary. Link to changed documentation:
- [x] Chaos pipeline run or not necessary. Link to pipeline:
- [x] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by etiennedi** [comment]
Hi @MarcusSorealheis, thanks for your contribution.

It seems like your commit doesn't rename the file but duplicates it. Could it be that you forgot to `git add` the old one? Can you still do this, please? Otherwise, we have the same twice with both names. 

Thanks

**Comment by MarcusSorealheis** [comment]
I try to use the UI tools and they never work. I'm too stuck in my ways. Fixed. Thanks.

**Comment by etiennedi** [comment]
Awesome, thanks. Now we only need a comment from you stating that you [agree with the CLA](https://github.com/semi-technologies/weaviate/pull/2409#issuecomment-1335917664), and I'm happy to merge.

**Comment by MarcusSorealheis** [comment]
I agree with the CLA

**Pull request merged**
