### PR TITLE
gh-000: Remove playground from Docker compose EN

### PR DESCRIPTION
**Pull request by bobvanluijt**
Based on user feedback (was confusing between online and docker file)

Installing the playground will be moved to separate docs.

### CODE REVIEW

**Comment by jettro** [comment]
Why do you remove the playground from the docker-compose? I think it was nice having it running on your local machine.

**Comment by bobvanluijt** [comment]
Publishing it as an independent Docker so that there is a clear distinction.

However, if including it makes it easier, we can set it to the latest by default in the compose file.

**Comment by jettro** [comment]
I personally like it to start everything with one single command

**Comment by bobvanluijt** [comment]
@jettro quick update here. We will be introducing the Weaviate Console soon which deprecates the Playground as a whole.

**Comment by kenaitian** [comment]
I understand that the Weaviate Console deprecates the Playground but when you’d follow the installation steps, it tells you to use “curl PUT... “ which didn’t work on the command prompt. The workaround for this was adding “localhost:8080” directly on  Playground from the browser for effect. An added concern is that I cannot find any material on how to implement any full stack application with Weaviate, let alone work with an existing application like with React or Node-Red.

**Comment by bobvanluijt** [comment]
Hi @kenaitian, thanks for the response, some questions.

> I understand that the Weaviate Console deprecates the Playground but when you’d follow the installation steps, it tells you to use “curl PUT... “ which didn’t work on the command prompt. The workaround for this was adding “localhost:8080” directly on Playground from the browser for effect.

I'm not sure that I understand what you mean, can you maybe elaborate a bit further?

> An added concern is that I cannot find any material on how to implement any full stack application with Weaviate, let alone work with an existing application like with React or Node-Red.

Also here I'm not 100% certain I understand the question, do you mean a front-end application using the Weaviate search engine features?

**Comment by kenaitian** [comment]
I followed through a combination of these steps mentioned below but to no
end. Also, I tried other tutorials as was related to apallo NPM among other
things but nothing worked...

**Comment by bobvanluijt** [comment]
Hi @kenaitian,

I'm not sure I understand the problem. Do I understand it correctly that you've got Weaviate to run but that you don't know how to access it in a Javascript application? If so, we could create a JS tutorial.

If you can share a bit more detail, we can help you get started.

**Comment by kenaitian** [comment]
That’s exactly what I was thinking provided that I tried a combination of
npm libraries that are supposed to work with GraphQL and essence access
weaviate but they didn’t work.

**Comment by bobvanluijt** [comment]
@kenaitian which one did you use? Any GraphQL lib should just work.

**Comment by kenaitian** [comment]
The React Apollo library but the syntax didn’t seem right to me.

**Comment by bobvanluijt** [comment]
@kenaitian here you go, this gets you started with querying: https://www.semi.technology/documentation/weaviate/current/client-libs/javascript.html

In case you want other features, please let us know [here](https://github.com/semi-technologies/weaviate-javascript-client/issues).

**Comment by bobvanluijt** [comment]
This one can stay closed – next week all will move to the console

**Pull request closed without merging**
